django_app/base/urls.py
from django.urls import path
from .views import *
# from django.views.generic import TemplateView

app_name = 'baseApp'
urlpatterns = [
    # path('departamental/', departamental, name='departamental'),
    # path('manzanas/', manzanas, name='manzanas'),
    path('indicadores/', indicadores, name='indicadores'),
    path('red/', red, name='red'),
    path('ayuda/', ayuda, name='ayuda'),
    path('simulacion/', simulacion, name='simulacion'),
    path('pruebas/', pruebas, name='pruebas'),
    path('prueba_mapas/agregar_punto/', agregar_punto, name='agregar_punto'),
    path('ajax/load-municipios/', load_municipios, name='ajax_load_municipios'),
    path('ajax/load-dimensiones/', load_dimensiones, name='ajax_load_dimensiones'),
    path('ajax/load-indicadores/', load_indicadores, name='ajax_load_indicadores'),

    # path('ajax/get-indicadores-data-municipal-map/', get_indicadores_data_municipal_map, name='ajax_get_indicadores_data_municipal_map'),
    # path('ajax/get-indicadores-data-departamental-map/', get_indicadores_data_departamental_map, name='ajax_get_indicadores_data_departamental_map'),
    path('ajax/get-data-indicadores-map/', get_data_indicadores_map, name='ajax_get_data_indicadores_map'),
    path('ajax/downloadExcel/', downloadExcel, name='ajax_downloadExcel'),
    path('ajax/downloadGeoJson/', downloadGeoJson, name='ajax_downloadGeoJson'),

    path('ajax/get-dimensiones-data-departamental-radar-1/', get_dimensiones_data_departamental_radar_1, name='ajax_get_dimensiones_data_departamental_radar_1'),
    path('ajax/get-dimensiones-data-departamental-radar-2/', get_dimensiones_data_departamental_radar_2, name='ajax_get_dimensiones_data_departamental_radar_2'),
]

django_app/salud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls, name='django-admin'),
    path('', include('base.urls')),
]

django_app/base/models.py
from django.db import models

class Punto_Salud(models.Model):    
    departamento = models.CharField(null=False, default='', max_length=255)
    municipio = models.CharField(null=False, default='', max_length=255)
    direccion = models.CharField(verbose_name='Dirección',null=False, default='', max_length=255)
    longitud = models.CharField(null=False, default='', max_length=255)
    latitud = models.CharField(null=False, default='', max_length=255)
    
    SI_NO_CHOICES =(('Sí', 'Sí'), ('No', 'No'))
    es_IPS = models.CharField(verbose_name='¿Esta sede pertenecerá o será una IPS?', choices=SI_NO_CHOICES, max_length=2, default='-')
    
    NATURALEZA_JURIDICA_CHOICES =(('Pública', 'Pública'), ('Privada', 'Privada'), ('Mixta', 'Mixta'))
    naturaleza_juridica = models.CharField(verbose_name='Naturaleza jurídica de la IPS', choices=NATURALEZA_JURIDICA_CHOICES, max_length=7, default='-')
    
    NIVEL_ATENCION_CHOICES =(('Primer nivel', 'Primer nivel'), ('Segundo nivel', 'Segundo nivel'), ('Tercer nivel', 'Tercer nivel'))
    nivel_atencion = models.CharField(verbose_name='Nivel de atención (Si es pública)', choices=NIVEL_ATENCION_CHOICES, max_length=13, default='-')

    ENTIDAD_TERRITORIAL_CHOICES =(('Municipal', 'Municipal'), ('Departamental', 'Departamental'))
    entidad_territorial = models.CharField(verbose_name='Entidad territorial a la que pertenece', choices=ENTIDAD_TERRITORIAL_CHOICES, max_length=13, default='-')

    TIPO_SERVICIOS_CHOICES =(('Primario', 'Primario'), ('Complementario', 'Complementario'))
    tipo_servicios = models.CharField(verbose_name='Tipo de servicios', choices=TIPO_SERVICIOS_CHOICES, max_length=14, default='-')

    class Meta:
        verbose_name = "Punto de salud"
        verbose_name_plural = "Puntos de salud"

    # def save(self, *args, **kwargs):
    #     try:
    #         this = Doc_Template.objects.get(id=self.id)
    #         if this.template != self.template:
    #             this.template.delete(save=False)
    #     except: pass
    #     super(Doc_Template, self).save(*args, **kwargs)

    # def __str__(self):
    #     return str(self.pk)


class Departamento(models.Model):
    divipola = models.CharField(max_length=2, unique=True)
    nombre = models.CharField(null=False, default='', max_length=255)

    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return self.nombre


class Municipio(models.Model):
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    divipola = models.CharField(max_length=5, unique=True)
    nombre = models.CharField(null=False, default='', max_length=255)

    class Meta:
        ordering = ['departamento', 'nombre']

    def __str__(self):
        return f"{self.departamento.nombre} - {self.nombre}"


class Manzana(models.Model):
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    divipola = models.CharField(max_length=22, unique=True)
    # nombre = models.CharField(null=False, default='', max_length=255)

    class Meta:
        ordering = ['divipola']

    def __str__(self):
        return f"{self.municipio.nombre} - {self.divipola}"


class Dimension(models.Model):
    nombre = models.CharField(null=False, default='', max_length=255)
    
    class Meta:
        verbose_name = "Dimensión"
        verbose_name_plural = "Dimensiones"
        ordering = ['nombre']

    def __str__(self):
        return self.nombre


class Indicador(models.Model):
    dimension = models.ForeignKey(Dimension, on_delete=models.CASCADE)
    nombre = models.CharField(null=False, default='', max_length=255)
    es_porcentual = models.BooleanField(default=False)
    
    class Meta:
        verbose_name = "Indicador"
        verbose_name_plural = "Indicadores"
        ordering = ['dimension', 'nombre']

    def __str__(self):
        return f"{self.dimension.nombre} - {self.nombre}"


class RegistroIndiceDepartamental(models.Model):
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    indicador = models.ForeignKey(Indicador, on_delete=models.CASCADE)
    valor = models.FloatField()

    class Meta:
        verbose_name = "Registro índice - Departamental"
        verbose_name_plural = "Registros índices - Departamental"
        ordering = ['indicador', 'departamento']

    def __str__(self):
        return f"{self.indicador} - {self.departamento}"


class RegistroIndiceMunicipal(models.Model):
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    indicador = models.ForeignKey(Indicador, on_delete=models.CASCADE)
    valor = models.FloatField()

    class Meta:
        verbose_name = "Registro índice - Municipal"
        verbose_name_plural = "Registros índices - Municipal"
        ordering = ['indicador', 'municipio']

    def __str__(self):
        return f"{self.indicador} - {self.municipio}"


class RegistroIndiceManzana(models.Model):
    manzana = models.ForeignKey(Manzana, on_delete=models.CASCADE)
    indicador = models.ForeignKey(Indicador, on_delete=models.CASCADE)
    valor = models.FloatField()

    class Meta:
        verbose_name = "Registro índice - Manzana"
        verbose_name_plural = "Registros índices - Manzana"
        ordering = ['indicador', 'manzana']

    def __str__(self):
        return f"{self.indicador} - {self.manzana}"

django_app/base/forms.py
from django import forms
from .models import Punto_Salud

class Punto_Salud_Create_Form(forms.ModelForm):
    class Meta:
        model = Punto_Salud
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(Punto_Salud_Create_Form, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control form-control-sm'})

django_app/base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.core import serializers

from .forms import Punto_Salud_Create_Form
from .models import *

from io import BytesIO
import random
import pandas as pd
import numpy as np
import geopandas as gpd

from django.templatetags.static import static


def color_map(value, colores, rangos):
    index = 0
    for idx, val in enumerate(rangos[:-1]):
        if (float(value) > float(rangos[idx+1])) and (float(value) <= float(rangos[idx])):
            index = idx
    
    if float(value) == 0.0:
        return colores[-1]

    return colores[index]

def update_rangos(rangos, es_porcentual):
    temp = []
    for idx, value in enumerate(rangos[:-1]):
        if es_porcentual:
            temp.append(f'{rangos[idx+1]} - {rangos[idx]} %')
        else:
            temp.append(f'{rangos[idx+1]:,} - {rangos[idx]:,}'.replace(',','.'))

    if es_porcentual:
        temp.append('0 %')
    else:
        temp.append('0')
    return temp

# def get_indicadores_data_municipal_map(request):
#     departamento = request.GET.get('departamento', None)
#     dimension = request.GET.get('dimension', None)
#     indicador = request.GET.get('indicador', None)

#     if departamento == '00':
#         departamentos = Departamento.objects.all()
#     else:
#         departamentos = Departamento.objects.filter(divipola=departamento)

#     departamentos_list = departamentos.values_list('pk', 'divipola', 'nombre', flat=False)
#     df_departamentos = pd.DataFrame.from_records(departamentos_list, columns=['departamento_pk', 'divipola_departamento', 'nombre_departamento'])
    
#     municipios = Municipio.objects.filter(departamento__in=departamentos)
#     municipios_list = municipios.values_list('pk', 'departamento', 'divipola', 'nombre', flat=False)
#     df_municipios = pd.DataFrame.from_records(municipios_list, columns=['municipio_pk', 'departamento_pk', 'divipola_municipio', 'nombre_municipio'])
    
#     registros = RegistroIndiceMunicipal.objects.filter(municipio__departamento__in=departamentos, indicador=indicador)
#     registros_list = registros.values_list('pk', 'municipio', 'indicador', 'valor', flat=False)
#     df_registros = pd.DataFrame.from_records(registros_list, columns=['registro_pk', 'municipio_pk', 'indicador_pk', 'valor_indicador'])

#     indicadores = Indicador.objects.filter(pk=indicador)
#     indicadores_list = indicadores.values_list('pk', 'dimension', 'nombre', flat=False)
#     df_indicadores = pd.DataFrame.from_records(indicadores_list, columns=['indicador_pk', 'dimension_pk', 'nombre_indicador'])

#     dimensiones = Dimension.objects.filter(pk=dimension)
#     dimensiones_list = dimensiones.values_list('pk', 'nombre', flat=False)
#     df_dimensiones = pd.DataFrame.from_records(dimensiones_list, columns=['dimension_pk', 'nombre_dimension'])

#     df_temp = df_registros.merge(df_municipios, on='municipio_pk', how="left")
#     df_temp = df_temp.merge(df_departamentos, on='departamento_pk', how="left")
#     df_temp = df_temp.merge(df_indicadores, on='indicador_pk', how="left")
#     df_temp = df_temp.merge(df_dimensiones, on='dimension_pk', how="left")

#     df_temp.rename(columns={"nombre_municipio": "nombre_ubicacion"}, inplace=True)

#     colores = ['#a50026', '#d73027', '#f46d43', '#fdae61', '#fee090', '#e0f3f8', '#abd9e9', '#74add1', '#4575b4', '#313695', '#575756']

#     if indicadores[0].es_porcentual:
#         rangos = [100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 0]
#         df_temp['color'] = df_temp['valor_indicador'].map(lambda valor: color_map(valor, colores, rangos))
#         rangos = update_rangos(rangos, True)
#     else:
#         rangos = np.quantile(list(df_temp['valor_indicador']), q = np.arange(0.1, 1, 0.1)).tolist()
#         rangos.append(df_temp['valor_indicador'].max())
#         rangos = [round(item) for item in rangos]
#         rangos.insert(0, 0)
#         rangos.reverse()
#         df_temp['color'] = df_temp['valor_indicador'].map(lambda valor: color_map(valor, colores, rangos))
#         rangos = update_rangos(rangos, False)

#     # print(df_temp.head(50))

#     data = {}
#     data['filter_records']=df_temp.to_dict('records')
#     data['legend_colors'] = colores
#     data['legend_values'] = rangos

#     return JsonResponse(data, safe=False)


# def get_indicadores_data_departamental_map(request):
#     departamento = request.GET.get('departamento', None)
#     dimension = request.GET.get('dimension', None)
#     indicador = request.GET.get('indicador', None)

#     if departamento == '00':
#         departamentos = Departamento.objects.all()
#     else:
#         departamentos = Departamento.objects.filter(divipola=departamento)

#     departamentos_list = departamentos.values_list('pk', 'divipola', 'nombre', flat=False)
#     df_departamentos = pd.DataFrame.from_records(departamentos_list, columns=['departamento_pk', 'divipola_departamento', 'nombre_departamento'])

#     # municipios = Municipio.objects.filter(departamento__in=departamentos)
#     # municipios_list = municipios.values_list('pk', 'departamento', 'divipola', 'nombre', flat=False)
#     # df_municipios = pd.DataFrame.from_records(municipios_list, columns=['municipio_pk', 'departamento_pk', 'divipola_municipio', 'nombre_municipio'])

#     registros = RegistroIndiceDepartamental.objects.filter(departamento__in=departamentos, indicador=indicador)
#     registros_list = registros.values_list('pk', 'departamento', 'indicador', 'valor', flat=False)
#     df_registros = pd.DataFrame.from_records(registros_list, columns=['registro_pk', 'departamento_pk', 'indicador_pk', 'valor_indicador'])

#     indicadores = Indicador.objects.filter(pk=indicador)
#     indicadores_list = indicadores.values_list('pk', 'dimension', 'nombre', flat=False)
#     df_indicadores = pd.DataFrame.from_records(indicadores_list, columns=['indicador_pk', 'dimension_pk', 'nombre_indicador'])

#     dimensiones = Dimension.objects.filter(pk=dimension)
#     dimensiones_list = dimensiones.values_list('pk', 'nombre', flat=False)
#     df_dimensiones = pd.DataFrame.from_records(dimensiones_list, columns=['dimension_pk', 'nombre_dimension'])

#     # df_temp = df_registros.merge(df_municipios, on='municipio_pk', how="left")
#     df_temp = df_registros.merge(df_departamentos, on='departamento_pk', how="left")
#     df_temp = df_temp.merge(df_indicadores, on='indicador_pk', how="left")
#     df_temp = df_temp.merge(df_dimensiones, on='dimension_pk', how="left")

#     df_temp.rename(columns={"nombre_departamento": "nombre_ubicacion"}, inplace=True)

#     colores = ['#a50026', '#d73027', '#f46d43', '#fdae61', '#fee090', '#e0f3f8', '#abd9e9', '#74add1', '#4575b4', '#313695', '#575756']

#     if indicadores[0].es_porcentual:
#         rangos = [100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 0]
#         df_temp['color'] = df_temp['valor_indicador'].map(lambda valor: color_map(valor, colores, rangos))
#         rangos = update_rangos(rangos, True)
#     else:
#         rangos = np.quantile(list(df_temp['valor_indicador']), q = np.arange(0.1, 1, 0.1)).tolist()
#         rangos.append(df_temp['valor_indicador'].max())
#         rangos = [round(item) for item in rangos]
#         rangos.insert(0, 0)
#         rangos.reverse()
#         df_temp['color'] = df_temp['valor_indicador'].map(lambda valor: color_map(valor, colores, rangos))
#         rangos = update_rangos(rangos, False)

#     # print(list(df_temp))
#     # print(df_temp.head(50))

#     data = {}
#     data['filter_records']=df_temp.to_dict('records')
#     data['legend_colors'] = colores
#     data['legend_values'] = rangos

#     return JsonResponse(data, safe=False)

def get_data_indicadores_map(request, return_df=False, include_divipola_id=False):
    # print('::: def get_data_indicadores_map')
    departamento = request.GET.get('departamento', None)
    municipio = request.GET.get('municipio', None)
    dimension = request.GET.get('dimension', None)
    indicador = request.GET.get('indicador', None)
    # print('municipio:', municipio)
    if departamento == '00':
        # Vista Nacional - se visualiza la info por departamentos

        departamentos = Departamento.objects.all()
        departamentos_list = departamentos.values_list('pk', 'divipola', 'nombre', flat=False)
        df_departamentos = pd.DataFrame.from_records(departamentos_list, columns=['departamento_pk', 'divipola_departamento', 'nombre_departamento'])

        registros = RegistroIndiceDepartamental.objects.filter(departamento__in=departamentos, indicador=indicador)
        registros_list = registros.values_list('pk', 'departamento', 'indicador', 'valor', flat=False)
        df_registros = pd.DataFrame.from_records(registros_list, columns=['registro_pk', 'departamento_pk', 'indicador_pk', 'valor_indicador'])

        indicadores = Indicador.objects.filter(pk=indicador)
        indicadores_list = indicadores.values_list('pk', 'dimension', 'nombre', flat=False)
        df_indicadores = pd.DataFrame.from_records(indicadores_list, columns=['indicador_pk', 'dimension_pk', 'nombre_indicador'])

        dimensiones = Dimension.objects.filter(pk=dimension)
        dimensiones_list = dimensiones.values_list('pk', 'nombre', flat=False)
        df_dimensiones = pd.DataFrame.from_records(dimensiones_list, columns=['dimension_pk', 'nombre_dimension'])

        df_temp = df_registros.merge(df_departamentos, on='departamento_pk', how="left")
    
    elif (municipio != '') and (municipio != '000') and (municipio is not None):

        # Vista Municipal - se visualiza la info por manzanas

        departamentos = Departamento.objects.filter(divipola=departamento)
        departamentos_list = departamentos.values_list('pk', 'divipola', 'nombre', flat=False)

django_app/base/templates/base/items_dropdown_list_options.html
{% if with_default %}
    <option value="000" selected>----------</option>
{% endif %}
{% for item in items %}    
    {% if with_default %}
        <option value="{{ item.pk }}">{{ item.nombre }}</option>            
    {% else %}
        {% if forloop.first %}
            <option value="{{ item.pk }}" selected>{{ item.nombre }}</option>
        {% else %}
            <option value="{{ item.pk }}">{{ item.nombre }}</option>
        {% endif %}        
    {% endif %}
{% endfor %}

django_app/base/templates/base/items_dropdown_list_options_municipios.html
{% if with_default %}
    <option value="000" selected>----------</option>
{% endif %}
{% for item in items %}    
    {% if with_default == 'True' %}
        {% if forloop.first %}
            <option value="{{ item.divipola }}" selected>{{ item.nombre }}</option>
        {% else %}
            <option value="{{ item.divipola }}">{{ item.nombre }}</option>
        {% endif %}
    {% else %}
        <option value="{{ item.divipola }}">{{ item.nombre }}</option>
    {% endif %}
{% endfor %}

django_app/base/templates/base/red.html
<!-- templates/red.html -->
{% extends 'base.html' %}
{% load static %}
{% block referencia %}red.html{% endblock %}
{% block title_1 %}Red{% endblock %}
{% block title_2 %}Red{% endblock %}

{% block content %}
<p>{{ mensaje }}</p>

{% endblock %}

django_app/base/templates/base/simulacion.html
<!-- templates/pruebas.html -->
{% extends 'base.html' %}
{% load static %}
{% block referencia %}pruebas.html{% endblock %}
{% block title_1 %}Pruebas{% endblock %}
{% block title_2 %}Formulario nuevo punto de atención en salud{% endblock %}

{% block content %}
<p>{{ mensaje }}</p>

	<div class="row">
		<div class="col-md-4">
			{% comment %} <a class="boton" title="Agregar" href="{% url 'baseApp:crear-mapa' %}">Agregar <i class="fas fa-plus verde"></i></a> {% endcomment %}
		</div>
		<div class="col-md-8">
		</div>
	</div>

	<div class="row">

		<div class="col-md-5">
			<form action="" method="POST">
				{% csrf_token %}
				{{ form }}
				<br>
				<button type="submit" class="btn btn-success"></i>Agregar punto de atención</button>
				<button class="btn btn-danger"></i>Cancelar</button>
			</form>	
		</div>

		<div class="col-md-7">				
			<div id="map" style="height: 560px;"></div>
			<div><a href="https://leaflet-extras.github.io/leaflet-providers/preview/" target="_blank">https://leaflet-extras.github.io/leaflet-providers/preview/</a></div>
			<div><a href="https://leafletjs.com/examples/quick-start/" target="_blank">https://leafletjs.com/examples/quick-start/</a></div>	
		</div>

	</div>
	
	<script>
		var map = L.map('map').setView([4.683709901063048, -74.05116825770746], 16);
		
		L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
			maxZoom: 19,
			attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
		}).addTo(map);

		{% comment %} 
		var marker = L.marker([4.6825, -74.055]).addTo(map);

		var circle = L.circle([4.6825, -74.055], {
			color: 'red',
			fillColor: '#f03',
			fillOpacity: 0.5,
			radius: 100
		}).addTo(map); 
		{% endcomment %}

		{% comment %} marker.bindPopup("<b>Hello world!</b><br>I am a popup.").openPopup(); {% endcomment %}
		{% comment %} circle.bindPopup("I am a circle."); {% endcomment %}

		var popup = L.popup();
		function onMapClick(e) {
			

			// console.log(e.latlng.toString());
			// console.log(e);

			$.ajax({
				url: '{% url "baseApp:agregar_punto" %}',
				data: {'latitud': e.latlng.lat, 'longitud': e.latlng.lng},
				dataType: 'json',

				success: function (data) {
					var latitud = JSON.parse(data.latitud);
					var longitud = JSON.parse(data.longitud);
					var radio = JSON.parse(data.radio);
					var color = JSON.parse(JSON.stringify(data.color));

					var circle = L.circle([latitud, longitud], {
						color: color,
						fillColor: color,
						fillOpacity: 0.5,
						radius: radio
					}).addTo(map);

					//circle.bindPopup(
					circle.bindTooltip(
						"<div class='leaflet-tooltip-own'>" +
							"<p style='text-transform: uppercase;'><strong>Centro prestador de servicios médicos</strong></p>" +
							"<table>" +
								"<tr>" +
									"<th>Variable</th>" +
									"<th>Valor</th>" +
								"</tr>" +
								"<tr>" +
									"<td><strong>Latitud:</strong></td>" +
									"<td>" + latitud + "</td>" +
								"</tr>" +
								"<tr>" +
									"<td><strong>Longitud:</strong></td>" +
									"<td>" + longitud + "</td>" +
								"</tr>" +
								"<tr>" +
									"<td><strong>Cobertura:</strong></td>" +
									"<td>" + "<span style='color:red'>" + radio + ' metros</span>' + "</td>" +
								"</tr>" +
							"</table>" +
						"</div>"
					);

					// popup
					// 	.setLatLng(e.latlng)
					// 	.setContent("Se agregó un punto en las coordenadas: <strong>" + latitud + ', ' + longitud + "</strong> con un radio de <span style='color:red'><strong>cobertura de " + radio + ' metros </strong></span>')
					// 	.openOn(map);

				},
				error: function (res) {
					console.log(res.responseText);
				}
			});
		}

		map.on('click', onMapClick);

    </script>
{% endblock %}