django_app/base/urls.py
from django.urls import path
from .views import *
# from django.views.generic import TemplateView

app_name = 'baseApp'
urlpatterns = [
    # path('departamental/', departamental, name='departamental'),
    # path('manzanas/', manzanas, name='manzanas'),
    path('indicadores/', indicadores, name='indicadores'),
    path('red/', red, name='red'),
    path('ayuda/', ayuda, name='ayuda'),
    path('simulacion/', simulacion, name='simulacion'),
    path('pruebas/', pruebas, name='pruebas'),
    path('prueba_mapas/agregar_punto/', agregar_punto, name='agregar_punto'),
    path('ajax/load-municipios/', load_municipios, name='ajax_load_municipios'),
    path('ajax/load-dimensiones/', load_dimensiones, name='ajax_load_dimensiones'),
    path('ajax/load-indicadores/', load_indicadores, name='ajax_load_indicadores'),

    # path('ajax/get-indicadores-data-municipal-map/', get_indicadores_data_municipal_map, name='ajax_get_indicadores_data_municipal_map'),
    # path('ajax/get-indicadores-data-departamental-map/', get_indicadores_data_departamental_map, name='ajax_get_indicadores_data_departamental_map'),
    path('ajax/get-data-indicadores-map/', get_data_indicadores_map, name='ajax_get_data_indicadores_map'),
    path('ajax/downloadExcel/', downloadExcel, name='ajax_downloadExcel'),
    path('ajax/downloadGeoJson/', downloadGeoJson, name='ajax_downloadGeoJson'),

    path('ajax/get-dimensiones-data-departamental-radar-1/', get_dimensiones_data_departamental_radar_1, name='ajax_get_dimensiones_data_departamental_radar_1'),
    path('ajax/get-dimensiones-data-departamental-radar-2/', get_dimensiones_data_departamental_radar_2, name='ajax_get_dimensiones_data_departamental_radar_2'),
]

django_app/salud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls, name='django-admin'),
    path('', include('base.urls')),
]

django_app/base/models.py
from django.db import models

class Punto_Salud(models.Model):    
    departamento = models.CharField(null=False, default='', max_length=255)
    municipio = models.CharField(null=False, default='', max_length=255)
    direccion = models.CharField(verbose_name='Dirección',null=False, default='', max_length=255)
    longitud = models.CharField(null=False, default='', max_length=255)
    latitud = models.CharField(null=False, default='', max_length=255)
    
    SI_NO_CHOICES =(('Sí', 'Sí'), ('No', 'No'))
    es_IPS = models.CharField(verbose_name='¿Esta sede pertenecerá o será una IPS?', choices=SI_NO_CHOICES, max_length=2, default='-')
    
    NATURALEZA_JURIDICA_CHOICES =(('Pública', 'Pública'), ('Privada', 'Privada'), ('Mixta', 'Mixta'))
    naturaleza_juridica = models.CharField(verbose_name='Naturaleza jurídica de la IPS', choices=NATURALEZA_JURIDICA_CHOICES, max_length=7, default='-')
    
    NIVEL_ATENCION_CHOICES =(('Primer nivel', 'Primer nivel'), ('Segundo nivel', 'Segundo nivel'), ('Tercer nivel', 'Tercer nivel'))
    nivel_atencion = models.CharField(verbose_name='Nivel de atención (Si es pública)', choices=NIVEL_ATENCION_CHOICES, max_length=13, default='-')

    ENTIDAD_TERRITORIAL_CHOICES =(('Municipal', 'Municipal'), ('Departamental', 'Departamental'))
    entidad_territorial = models.CharField(verbose_name='Entidad territorial a la que pertenece', choices=ENTIDAD_TERRITORIAL_CHOICES, max_length=13, default='-')

    TIPO_SERVICIOS_CHOICES =(('Primario', 'Primario'), ('Complementario', 'Complementario'))
    tipo_servicios = models.CharField(verbose_name='Tipo de servicios', choices=TIPO_SERVICIOS_CHOICES, max_length=14, default='-')

    class Meta:
        verbose_name = "Punto de salud"
        verbose_name_plural = "Puntos de salud"

    # def save(self, *args, **kwargs):
    #     try:
    #         this = Doc_Template.objects.get(id=self.id)
    #         if this.template != self.template:
    #             this.template.delete(save=False)
    #     except: pass
    #     super(Doc_Template, self).save(*args, **kwargs)

    # def __str__(self):
    #     return str(self.pk)


class Departamento(models.Model):
    divipola = models.CharField(max_length=2, unique=True)
    nombre = models.CharField(null=False, default='', max_length=255)

    class Meta:
        ordering = ['nombre']

    def __str__(self):
        return self.nombre


class Municipio(models.Model):
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    divipola = models.CharField(max_length=5, unique=True)
    nombre = models.CharField(null=False, default='', max_length=255)

    class Meta:
        ordering = ['departamento', 'nombre']

    def __str__(self):
        return f"{self.departamento.nombre} - {self.nombre}"


class Manzana(models.Model):
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    divipola = models.CharField(max_length=22, unique=True)
    # nombre = models.CharField(null=False, default='', max_length=255)

    class Meta:
        ordering = ['divipola']

    def __str__(self):
        return f"{self.municipio.nombre} - {self.divipola}"


class Dimension(models.Model):
    nombre = models.CharField(null=False, default='', max_length=255)
    
    class Meta:
        verbose_name = "Dimensión"
        verbose_name_plural = "Dimensiones"
        ordering = ['nombre']

    def __str__(self):
        return self.nombre


class Indicador(models.Model):
    dimension = models.ForeignKey(Dimension, on_delete=models.CASCADE)
    nombre = models.CharField(null=False, default='', max_length=255)
    es_porcentual = models.BooleanField(default=False)
    
    class Meta:
        verbose_name = "Indicador"
        verbose_name_plural = "Indicadores"
        ordering = ['dimension', 'nombre']

    def __str__(self):
        return f"{self.dimension.nombre} - {self.nombre}"


class RegistroIndiceDepartamental(models.Model):
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    indicador = models.ForeignKey(Indicador, on_delete=models.CASCADE)
    valor = models.FloatField()

    class Meta:
        verbose_name = "Registro índice - Departamental"
        verbose_name_plural = "Registros índices - Departamental"
        ordering = ['indicador', 'departamento']

    def __str__(self):
        return f"{self.indicador} - {self.departamento}"


class RegistroIndiceMunicipal(models.Model):
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    indicador = models.ForeignKey(Indicador, on_delete=models.CASCADE)
    valor = models.FloatField()

    class Meta:
        verbose_name = "Registro índice - Municipal"
        verbose_name_plural = "Registros índices - Municipal"
        ordering = ['indicador', 'municipio']

    def __str__(self):
        return f"{self.indicador} - {self.municipio}"


class RegistroIndiceManzana(models.Model):
    manzana = models.ForeignKey(Manzana, on_delete=models.CASCADE)
    indicador = models.ForeignKey(Indicador, on_delete=models.CASCADE)
    valor = models.FloatField()

    class Meta:
        verbose_name = "Registro índice - Manzana"
        verbose_name_plural = "Registros índices - Manzana"
        ordering = ['indicador', 'manzana']

    def __str__(self):
        return f"{self.indicador} - {self.manzana}"

django_app/base/forms.py
from django import forms
from .models import Punto_Salud

class Punto_Salud_Create_Form(forms.ModelForm):
    class Meta:
        model = Punto_Salud
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(Punto_Salud_Create_Form, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control form-control-sm'})

django_app/base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from django.core import serializers

from .forms import Punto_Salud_Create_Form
from .models import *

from io import BytesIO
import random
import pandas as pd
import numpy as np
import geopandas as gpd

from django.templatetags.static import static


def color_map(value, colores, rangos):
    index = 0
    for idx, val in enumerate(rangos[:-1]):
        if (float(value) > float(rangos[idx+1])) and (float(value) <= float(rangos[idx])):
            index = idx
    
    if float(value) == 0.0:
        return colores[-1]

    return colores[index]

def update_rangos(rangos, es_porcentual):
    temp = []
    for idx, value in enumerate(rangos[:-1]):
        if es_porcentual:
            temp.append(f'{rangos[idx+1]} - {rangos[idx]} %')
        else:
            temp.append(f'{rangos[idx+1]:,} - {rangos[idx]:,}'.replace(',','.'))

    if es_porcentual:
        temp.append('0 %')
    else:
        temp.append('0')
    return temp

# def get_indicadores_data_municipal_map(request):
#     departamento = request.GET.get('departamento', None)
#     dimension = request.GET.get('dimension', None)
#     indicador = request.GET.get('indicador', None)

#     if departamento == '00':
#         departamentos = Departamento.objects.all()
#     else:
#         departamentos = Departamento.objects.filter(divipola=departamento)

#     departamentos_list = departamentos.values_list('pk', 'divipola', 'nombre', flat=False)
#     df_departamentos = pd.DataFrame.from_records(departamentos_list, columns=['departamento_pk', 'divipola_departamento', 'nombre_departamento'])
    
#     municipios = Municipio.objects.filter(departamento__in=departamentos)
#     municipios_list = municipios.values_list('pk', 'departamento', 'divipola', 'nombre', flat=False)
#     df_municipios = pd.DataFrame.from_records(municipios_list, columns=['municipio_pk', 'departamento_pk', 'divipola_municipio', 'nombre_municipio'])
    
#     registros = RegistroIndiceMunicipal.objects.filter(municipio__departamento__in=departamentos, indicador=indicador)
#     registros_list = registros.values_list('pk', 'municipio', 'indicador', 'valor', flat=False)
#     df_registros = pd.DataFrame.from_records(registros_list, columns=['registro_pk', 'municipio_pk', 'indicador_pk', 'valor_indicador'])

#     indicadores = Indicador.objects.filter(pk=indicador)
#     indicadores_list = indicadores.values_list('pk', 'dimension', 'nombre', flat=False)
#     df_indicadores = pd.DataFrame.from_records(indicadores_list, columns=['indicador_pk', 'dimension_pk', 'nombre_indicador'])

#     dimensiones = Dimension.objects.filter(pk=dimension)
#     dimensiones_list = dimensiones.values_list('pk', 'nombre', flat=False)
#     df_dimensiones = pd.DataFrame.from_records(dimensiones_list, columns=['dimension_pk', 'nombre_dimension'])

#     df_temp = df_registros.merge(df_municipios, on='municipio_pk', how="left")
#     df_temp = df_temp.merge(df_departamentos, on='departamento_pk', how="left")
#     df_temp = df_temp.merge(df_indicadores, on='indicador_pk', how="left")
#     df_temp = df_temp.merge(df_dimensiones, on='dimension_pk', how="left")

#     df_temp.rename(columns={"nombre_municipio": "nombre_ubicacion"}, inplace=True)

#     colores = ['#a50026', '#d73027', '#f46d43', '#fdae61', '#fee090', '#e0f3f8', '#abd9e9', '#74add1', '#4575b4', '#313695', '#575756']

#     if indicadores[0].es_porcentual:
#         rangos = [100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 0]
#         df_temp['color'] = df_temp['valor_indicador'].map(lambda valor: color_map(valor, colores, rangos))
#         rangos = update_rangos(rangos, True)
#     else:
#         rangos = np.quantile(list(df_temp['valor_indicador']), q = np.arange(0.1, 1, 0.1)).tolist()
#         rangos.append(df_temp['valor_indicador'].max())
#         rangos = [round(item) for item in rangos]
#         rangos.insert(0, 0)
#         rangos.reverse()
#         df_temp['color'] = df_temp['valor_indicador'].map(lambda valor: color_map(valor, colores, rangos))
#         rangos = update_rangos(rangos, False)

#     # print(df_temp.head(50))

#     data = {}
#     data['filter_records']=df_temp.to_dict('records')
#     data['legend_colors'] = colores
#     data['legend_values'] = rangos

#     return JsonResponse(data, safe=False)


# def get_indicadores_data_departamental_map(request):
#     departamento = request.GET.get('departamento', None)
#     dimension = request.GET.get('dimension', None)
#     indicador = request.GET.get('indicador', None)

#     if departamento == '00':
#         departamentos = Departamento.objects.all()
#     else:
#         departamentos = Departamento.objects.filter(divipola=departamento)

#     departamentos_list = departamentos.values_list('pk', 'divipola', 'nombre', flat=False)
#     df_departamentos = pd.DataFrame.from_records(departamentos_list, columns=['departamento_pk', 'divipola_departamento', 'nombre_departamento'])

#     # municipios = Municipio.objects.filter(departamento__in=departamentos)
#     # municipios_list = municipios.values_list('pk', 'departamento', 'divipola', 'nombre', flat=False)
#     # df_municipios = pd.DataFrame.from_records(municipios_list, columns=['municipio_pk', 'departamento_pk', 'divipola_municipio', 'nombre_municipio'])

#     registros = RegistroIndiceDepartamental.objects.filter(departamento__in=departamentos, indicador=indicador)
#     registros_list = registros.values_list('pk', 'departamento', 'indicador', 'valor', flat=False)
#     df_registros = pd.DataFrame.from_records(registros_list, columns=['registro_pk', 'departamento_pk', 'indicador_pk', 'valor_indicador'])

#     indicadores = Indicador.objects.filter(pk=indicador)
#     indicadores_list = indicadores.values_list('pk', 'dimension', 'nombre', flat=False)
#     df_indicadores = pd.DataFrame.from_records(indicadores_list, columns=['indicador_pk', 'dimension_pk', 'nombre_indicador'])

#     dimensiones = Dimension.objects.filter(pk=dimension)
#     dimensiones_list = dimensiones.values_list('pk', 'nombre', flat=False)
#     df_dimensiones = pd.DataFrame.from_records(dimensiones_list, columns=['dimension_pk', 'nombre_dimension'])

#     # df_temp = df_registros.merge(df_municipios, on='municipio_pk', how="left")
#     df_temp = df_registros.merge(df_departamentos, on='departamento_pk', how="left")
#     df_temp = df_temp.merge(df_indicadores, on='indicador_pk', how="left")
#     df_temp = df_temp.merge(df_dimensiones, on='dimension_pk', how="left")

#     df_temp.rename(columns={"nombre_departamento": "nombre_ubicacion"}, inplace=True)

#     colores = ['#a50026', '#d73027', '#f46d43', '#fdae61', '#fee090', '#e0f3f8', '#abd9e9', '#74add1', '#4575b4', '#313695', '#575756']

#     if indicadores[0].es_porcentual:
#         rangos = [100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 0]
#         df_temp['color'] = df_temp['valor_indicador'].map(lambda valor: color_map(valor, colores, rangos))
#         rangos = update_rangos(rangos, True)
#     else:
#         rangos = np.quantile(list(df_temp['valor_indicador']), q = np.arange(0.1, 1, 0.1)).tolist()
#         rangos.append(df_temp['valor_indicador'].max())
#         rangos = [round(item) for item in rangos]
#         rangos.insert(0, 0)
#         rangos.reverse()
#         df_temp['color'] = df_temp['valor_indicador'].map(lambda valor: color_map(valor, colores, rangos))
#         rangos = update_rangos(rangos, False)

#     # print(list(df_temp))
#     # print(df_temp.head(50))

#     data = {}
#     data['filter_records']=df_temp.to_dict('records')
#     data['legend_colors'] = colores
#     data['legend_values'] = rangos

#     return JsonResponse(data, safe=False)

def get_data_indicadores_map(request, return_df=False, include_divipola_id=False):
    # print('::: def get_data_indicadores_map')
    departamento = request.GET.get('departamento', None)
    municipio = request.GET.get('municipio', None)
    dimension = request.GET.get('dimension', None)
    indicador = request.GET.get('indicador', None)
    # print('municipio:', municipio)
    if departamento == '00':
        # Vista Nacional - se visualiza la info por departamentos

        departamentos = Departamento.objects.all()
        departamentos_list = departamentos.values_list('pk', 'divipola', 'nombre', flat=False)
        df_departamentos = pd.DataFrame.from_records(departamentos_list, columns=['departamento_pk', 'divipola_departamento', 'nombre_departamento'])

        registros = RegistroIndiceDepartamental.objects.filter(departamento__in=departamentos, indicador=indicador)
        registros_list = registros.values_list('pk', 'departamento', 'indicador', 'valor', flat=False)
        df_registros = pd.DataFrame.from_records(registros_list, columns=['registro_pk', 'departamento_pk', 'indicador_pk', 'valor_indicador'])

        indicadores = Indicador.objects.filter(pk=indicador)
        indicadores_list = indicadores.values_list('pk', 'dimension', 'nombre', flat=False)
        df_indicadores = pd.DataFrame.from_records(indicadores_list, columns=['indicador_pk', 'dimension_pk', 'nombre_indicador'])

        dimensiones = Dimension.objects.filter(pk=dimension)
        dimensiones_list = dimensiones.values_list('pk', 'nombre', flat=False)
        df_dimensiones = pd.DataFrame.from_records(dimensiones_list, columns=['dimension_pk', 'nombre_dimension'])

        df_temp = df_registros.merge(df_departamentos, on='departamento_pk', how="left")
    
    elif (municipio != '') and (municipio != '000') and (municipio is not None):

        # Vista Municipal - se visualiza la info por manzanas

        departamentos = Departamento.objects.filter(divipola=departamento)
        departamentos_list = departamentos.values_list('pk', 'divipola', 'nombre', flat=False)

django_app/templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    {% comment %} <meta name="description" content="A simple HTML5 Template for new projects."> {% endcomment %}
    {% comment %} <meta name="author" content="SitePoint"> {% endcomment %}

    {% comment %} <meta property="og:title" content="A Basic HTML5 Template"> {% endcomment %}
    {% comment %} <meta property="og:type" content="website"> {% endcomment %}
    {% comment %} <meta property="og:url" content="https://www.sitepoint.com/a-basic-html5-template/"> {% endcomment %}
    {% comment %} <meta property="og:description" content="A simple HTML5 Template for new projects."> {% endcomment %}
    {% comment %} <meta property="og:image" content="image.png"> {% endcomment %}

    {% comment %} <link rel="icon" href="/favicon.ico"> {% endcomment %}
    {% comment %} <link rel="icon" href="/favicon.svg" type="image/svg+xml"> {% endcomment %}
    {% comment %} <link rel="apple-touch-icon" href="/apple-touch-icon.png"> {% endcomment %}

    <title>Accesibilidad a Servicios de Salud - {% block title_1 %}{% endblock %}</title>

    <!-- favicon -->
    <link href="{% static 'images/favicon_dnp.ico' %}" rel="icon" type="image/x-icon" />

    <!-- fontawesome -->
    <!-- <script src="https://kit.fontawesome.com/ed8b3e6f5e.js" crossorigin="anonymous"></script> -->
    <script type="text/javascript"> (function() { var css = document.createElement('link'); css.href = 'https://use.fontawesome.com/releases/v5.1.0/css/all.css'; css.rel = 'stylesheet'; css.type = 'text/css'; document.getElementsByTagName('head')[0].appendChild(css); })(); </script>

    <!-- Ajax jQuery -->
    {% comment %} <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script> {% endcomment %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>

    <!-- Bootstrap CSS v5.0 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/virtual-select.min.css' %}">

    <!-- My CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <!-- D3.js -->
    <script src="https://d3js.org/d3.v7.min.js"></script>

     <!-- Leaflet's CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
    integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
    crossorigin=""/>

    <!-- Leaflet's javascript -->
    <script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
    integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
    crossorigin=""></script>

    <!-- leaflet-easyPrint -->
    {% comment %} https://github.com/rowanwins/leaflet-easyPrint {% endcomment %}
    <script src="{% static 'js/bundle.js' %}"></script>

    <!-- Plotly -->
    <script src="https://cdn.plot.ly/plotly-2.12.1.min.js"></script>
</head>
<body>

    <!-- https://developer.mozilla.org/es/docs/Learn/Server-side/Django/Forms
    form.renewal_date: The whole field.
    form.renewal_date.errors: The list of errors.
    form.renewal_date.id_for_label: The id of the label.
    form.renewal_date.help_text: The field help text. -->

    <div class="container-fluid"> {% include 'navbar.html' %} </div>
    <div class="container-xxl my-contanier">
        <!-- <h5 style="margin:0px;">{% block referencia %}html_file.html{% endblock %}</h5><hr> -->
        <br>
        <h1>{% block title_2 %}{% endblock %}</h1>
        <hr>
        {% block content %}{% endblock %}
    </div>

    <!-- Footer -->
    <footer class="page-footer font-small pt-4">
        <hr style="margin:1px;">
        <div class="footer-copyright text-center py-3" style="padding-top: 10px !important;padding-bottom: 10px !important;">
            Proyecto Accesibilidad a Servicios de Salud - versión 2.0 - Desarrollado por la UCD 2022
        </div>
    </footer>

    <!-- Bootstrap Popper & Popper v5.0 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

django_app/templates/navbar.html
{% load static %}
<nav class="navbar navbar-light navbar-expand-lg fixed-top navbar-dnp">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="https://www.dnp.gov.co/estilos/images/logoNuevo.jpg" alt="" height="40px" class="d-inline-block align-text-top">
            <!-- <img src="{% static 'images/logo_pequeno.png' %}" alt="" height="35" class="d-inline-block align-text-top"> -->
            <!-- <span style="margin-left: 15px;">Mapas de brecha de evidencia</span> -->
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <a class="navbar-brand abs" href=""></a>
            <ul class="navbar-nav ms-auto">
                {% comment %} {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#"> Hola {{ request.user.first_name|title }} ({{ request.user.username }})</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Inicio</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Cerrar sesión</a></li>
                {% else %} {% endcomment %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'home' %}">Inicio</a></li>
                    {% comment %} <li class="nav-item"><a class="nav-link" href="{% url 'baseApp:departamental' %}">Departamental</a></li> {% endcomment %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'baseApp:indicadores' %}">Indicadores</a></li>
                    {% comment %} <li class="nav-item"><a class="nav-link" href="{% url 'baseApp:manzanas' %}">Por manzanas</a></li> {% endcomment %}
                    {% comment %} <li class="nav-item"><a class="nav-link" href="{% url 'baseApp:simulacion' %}">Simulación</a></li> {% endcomment %}
                    {% comment %} <li class="nav-item"><a class="nav-link" href="{% url 'baseApp:red' %}">Red</a></li> {% endcomment %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'baseApp:ayuda' %}">Ayuda</a></li>
                    {% comment %} <li class="nav-item"><a class="nav-link" href="{% url 'baseApp:pruebas' %}">pruebas</a></li> {% endcomment %}
                {% comment %} {% endif %} {% endcomment %}
            </ul>
        </div>
    </div>
</nav>
<div class="row fixed-top" style="margin-top:69px;">
    <div class="col-4 amarillo"></div>
    <div class="col-4 azul"></div>
    <div class="col-4 rojo"></div>
</div>

django_app/templates/pagination.html
{% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; primera</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">anterior</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="">&laquo; primera</a></li>
                <li class="page-item disabled"><a class="page-link" href="">anterior</a></li>
            {% endif %}

            <span class="current">
                <li class="page-item disabled"><a class="page-link" href="#">
                    página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
                </a></li>
            </span>
        
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">siguiente</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">última &raquo;</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="">siguiente</a></li>
                <li class="page-item disabled"><a class="page-link" href="">última &raquo;</a></li>
            {% endif %}

        </ul>
    </nav>
{% endif %}